# Generated by Django 4.0.4 on 2022-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='event',
            name='requiredNumber',
            field=models.IntegerField(default=0, verbose_name='Необходимое количество'),
        ),
        migrations.AddField(
            model_name='event',
            name='sportType',
            field=models.CharField(default='', max_length=20, verbose_name='Вид спорта'),
        ),
    ]
